const notAllowedCategoriesByBloodType = [
  {
    bloodType: '1',
    categories: [
      'non-alcoholic beverages',
      'oils and fats',
      'smoked products',
      'alcoholic beverages',
      'red meat',
      'berries',
      'fish',
      'fruits',
      'mushrooms',
      'nuts',
      'dried fruits',
      'vegetables and greens',
      'seeds',
      'sesame',
      'poppy',
    ],
  },
  {
    bloodType: '2',
    categories: [
      'red meat',
      'flour products',
      'oils and fats',
      'smoked products',
      'mushrooms',
      'eggs',
      'cereals',
      'non-alcoholic beverages',
      'alcoholic beverages',
      'berries',
      'fish',
      'fruits',
      'nuts',
      'dried fruits',
      'vegetables and greens',
      'seeds',
      'sesame',
      'poppy',
    ],
  },
  {
    bloodType: '3',
    categories: [
      'nuts',
      'dairy products',
      'red meat',
      'flour products',
      'non-alcoholic beverages',
      'eggs',
      'cereals',
      'oils and fats',
      'smoked products',
      'alcoholic beverages',
      'berries',
      'fish',
      'fruits',
      'mushrooms',
      'dried fruits',
      'vegetables and greens',
      'seeds',
      'sesame',
      'poppy',
    ],
  },
  {
    bloodType: '4',
    categories: [
      'eggs',
      'dairy products',
      'non-alcoholic beverages',
      'red meat',
      'alcoholic beverages',
      'cereals',
      'oils and fats',
      'smoked products',
      'flour products',
      'berries',
      'fish',
      'fruits',
      'mushrooms',
      'dried fruits',
      'vegetables and greens',
      'seeds',
      'sesame',
      'poppy',
    ],
  },
];

export const getCategoriesByBloodType = bloodType => {
  return notAllowedCategoriesByBloodType.find(
    item => item.bloodType === bloodType
  ).categories;
};
